name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          flake8 app.py
      - name: Lint with mypy
        run: |
          mypy app.py
      - name: Lint with black
        run: |
          black app.py
      - name: Lint with isort
        run: |
          isort app.py
      - name: Test with pytest
        run: |
          pytest test_main.py
